name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore project dependencies
      run: dotnet restore "FPL.Reminder/FPL.Reminder.csproj"
    - name: Build
      run: dotnet build "FPL.Reminder/FPL.Reminder.csproj"
    - name: Test
      run: dotnet test "FPL.Reminder.Tests/FPL.Reminder.Tests.csproj"
